MIRRN_redkiwi1024_maxlen4096_001_b4f7698b:
    accumulation_steps: 1
    attention_dim: 32
    attention_dropout: 0.1
    batch_norm: false
    batch_size: 2048
    dataset_id: redkiwi1024_maxlen4096
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 2
    eval_negative_sampling_ratio: -1
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 4
    train_sampling: undersampling
    train_sampling_ratio: 1.0
    use_features: null
    use_pos_weight: true
    use_scale: true
    verbose: 1
