MIRRN_redkiwi_001_0ef54b34:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [256, 128, 64]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 50
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/mirrn
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_redkiwi_002_7298c3d7:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 50
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/mirrn
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_redkiwi_003_be01d0eb:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [256, 128, 64]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 50
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 32
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/mirrn
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_redkiwi_004_12b6e668:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 50
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 32
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/mirrn
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
