Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 5
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

SDIM_default: # This is a config template
    model: SDIM
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 32
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_dim: 64
    use_qkvo: True
    num_heads: 2
    use_scale: True
    attention_dropout: 0
    reuse_hash: True
    num_hashes: 2
    hash_bits: 4
    net_dropout: 0
    batch_norm: False
    l2_norm: False
    epochs: 100
    shuffle: True
    seed: 20222023
    monitor: 'AUC'
    monitor_mode: 'max'
    short_seq_len: 50
    max_len: 50
    accumulation_steps: 1

SDIM_redkiwi:
    model: SDIM
    dataset_id: redkiwi
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'PRAUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 256
    embedding_dim: 32
    dnn_hidden_units: [256, 128, 64]
    dnn_activations: relu
    attention_dim: 64
    use_qkvo: True
    num_heads: 4
    use_scale: True
    attention_dropout: 0.1
    reuse_hash: True
    num_hashes: 2
    hash_bits: 4
    net_dropout: 0.1
    batch_norm: False
    l2_norm: False
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: 'PRACU'
    monitor_mode: 'max'
    short_seq_len: 10
    max_len: 50
    accumulation_steps: 1

SDIM_alipay:
    model: SDIM
    dataset_id: alipay
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'PRAUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 256
    embedding_dim: 32
    dnn_hidden_units: [256, 128, 64]
    dnn_activations: relu
    attention_dim: 64
    use_qkvo: True
    num_heads: 4
    use_scale: True
    attention_dropout: 0.1
    reuse_hash: True
    num_hashes: 2
    hash_bits: 4
    net_dropout: 0.1
    batch_norm: False
    l2_norm: False
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: 'PRACU'
    monitor_mode: 'max'
    short_seq_len: 10
    max_len: 500
    accumulation_steps: 1

SDIM_taobao:
    model: SDIM
    dataset_id: taobao
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'PRAUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 256
    embedding_dim: 32
    dnn_hidden_units: [256, 128, 64]
    dnn_activations: relu
    attention_dim: 64
    use_qkvo: True
    num_heads: 4
    use_scale: True
    attention_dropout: 0.1
    reuse_hash: True
    num_hashes: 2
    hash_bits: 4
    net_dropout: 0.1
    batch_norm: False
    l2_norm: False
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: 'PRACU'
    monitor_mode: 'max'
    short_seq_len: 10
    max_len: 500
    accumulation_steps: 1

SDIM_tmall:
    model: SDIM
    dataset_id: tmall
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'PRAUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 256
    embedding_dim: 32
    dnn_hidden_units: [256, 128, 64]
    dnn_activations: relu
    attention_dim: 64
    use_qkvo: True
    num_heads: 4
    use_scale: True
    attention_dropout: 0.1
    reuse_hash: True
    num_hashes: 2
    hash_bits: 4
    net_dropout: 0.1
    batch_norm: False
    l2_norm: False
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: 'PRACU'
    monitor_mode: 'max'
    short_seq_len: 10
    max_len: 500
    accumulation_steps: 1

SDIM_amazon:
    model: SDIM
    dataset_id: amazon
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'PRAUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 256
    embedding_dim: 32
    dnn_hidden_units: [256, 128, 64]
    dnn_activations: relu
    attention_dim: 64
    use_qkvo: True
    num_heads: 4
    use_scale: True
    attention_dropout: 0.1
    reuse_hash: True
    num_hashes: 2
    hash_bits: 4
    net_dropout: 0.1
    batch_norm: False
    l2_norm: False
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: 'PRACU'
    monitor_mode: 'max'
    short_seq_len: 10
    max_len: 500
    accumulation_steps: 1

SDIM_taobao_dmr:
    model: SDIM
    dataset_id: taobao_dmr
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'PRAUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 256
    embedding_dim: 32
    dnn_hidden_units: [256, 128, 64]
    dnn_activations: relu
    attention_dim: 64
    use_qkvo: True
    num_heads: 4
    use_scale: True
    attention_dropout: 0.1
    reuse_hash: True
    num_hashes: 2
    hash_bits: 4
    net_dropout: 0.1
    batch_norm: False
    l2_norm: False
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: 'PRACU'
    monitor_mode: 'max'
    short_seq_len: 10
    max_len: 500
    accumulation_steps: 1