taobao_maxlen512:
    data_format: parquet
    data_root: ../../data/taobao/maxlen512/
    feature_cols:
    - {active: true, dtype: int, name: user_index, type: meta, vocab_size: 1055077}
    - {active: true, dtype: int, name: item_index, type: meta, vocab_size: 12140}
    - {active: true, dtype: int, name: seq_len, type: meta}
    - {active: true, dtype: int, name: item_id, source: item, type: categorical, vocab_size: 12140}
    item_info: ../../data/taobao/maxlen512/item_info.parquet
    label_col: {dtype: float, name: label}
    rebuild_dataset: false
    test_data: ../../data/taobao/maxlen512/test_longctr.parquet
    train_data: ../../data/taobao/maxlen512/train_longctr.parquet
    user_info: ../../data/taobao/maxlen512/user_info.parquet
    valid_data: ../../data/taobao/maxlen512/valid_longctr.parquet
