ETA_redkiwi_001_82929c3f:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: false
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [256, 128, 64]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/eta
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
ETA_redkiwi_002_9cfea2e6:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: false
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/eta
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
ETA_redkiwi_003_a7e1e41f:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: false
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [256, 128, 64]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 32
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/eta
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
ETA_redkiwi_004_d34a876a:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: false
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 32
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/eta
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
