redkiwi512_maxlen1024:
    data_format: parquet
    data_root: ../../data/redkiwi512/maxlen1024/
    feature_cols:
    - {active: true, dtype: int, name: user_index, type: meta, vocab_size: 84648}
    - {active: true, dtype: int, name: item_index, type: meta, vocab_size: 601}
    - {active: true, dtype: int, name: seq_len, type: meta}
    - {active: true, dtype: int, name: item_id, source: item, type: categorical, vocab_size: 601}
    item_info: ../../data/redkiwi512/maxlen1024/item_info.parquet
    label_col: {dtype: float, name: label}
    rebuild_dataset: false
    test_data: ../../data/redkiwi512/maxlen1024/test_longctr.parquet
    train_data: ../../data/redkiwi512/maxlen1024/train_longctr.parquet
    user_info: ../../data/redkiwi512/maxlen1024/user_info.parquet
    valid_data: ../../data/redkiwi512/maxlen1024/valid_longctr.parquet
