SDIM_redkiwi_001_567207d2:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: false
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [256, 128, 64]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 4
    l2_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/sdim
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 2
    num_heads: 4
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_redkiwi_002_1e574584:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: false
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 4
    l2_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/sdim
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 2
    num_heads: 4
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_redkiwi_003_4622a7bf:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: false
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [256, 128, 64]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 4
    l2_norm: false
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/sdim
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 2
    num_heads: 4
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
SDIM_redkiwi_004_374250ad:
    accumulation_steps: 1
    attention_dim: 64
    attention_dropout: 0.1
    batch_norm: false
    batch_size: 256
    dataset_id: redkiwi
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 5
    embedding_dim: 32
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hash_bits: 4
    l2_norm: false
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 50
    metrics: [PRAUC, AUC, logloss]
    model: SDIM
    model_root: ./checkpoints/sdim
    monitor: {PRAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hashes: 2
    num_heads: 4
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: true
    save_best_only: true
    seed: 2025
    short_seq_len: 10
    shuffle: true
    task: binary_classification
    use_features: null
    use_qkvo: true
    use_scale: true
    verbose: 1
