base_config: ./config/mirrn_config/
base_expid: MIRRN_redkiwi
dataset_id: redkiwi

redkiwi:
    data_root: ../../data/
    data_format: parquet
    train_data: ../../data/redkiwi/train_longctr.parquet
    valid_data: ../../data/redkiwi/valid_longctr.parquet
    test_data: ../../data/redkiwi/test_longctr.parquet
    user_info: ../../data/redkiwi/user_info.parquet
    item_info: ../../data/redkiwi/item_info.parquet
    rebuild_dataset: False
    feature_cols:
        - {name: user_index, active: True, dtype: int, type: meta, vocab_size: 84648}
        - {name: item_index, active: True, dtype: int, type: meta, vocab_size: 601}
        - {name: seq_len, active: True, dtype: int, type: meta}
        - {name: item_id, active: True, dtype: int, type: categorical, source: item, vocab_size: 601}
    label_col: {name: label, dtype: float}

tuner_space:
    model_root: './checkpoints/'
    embedding_dim: 16
    dnn_hidden_units: [[256, 128, 64]]
    net_dropout: [0.2, 0.1, 0]
    batch_norm: False
    learning_rate: 5.e-4
    batch_size: 256
    seed: 2022
    metrics: [[PRAUC, AUC, logloss]]
    monitor: {"PRAUC": 1, "AUC": 1}
