redkiwi256_maxlen128:
    data_format: parquet
    data_root: ../../data/redkiwi256/maxlen128/
    feature_cols:
    - {active: true, dtype: int, name: user_index, type: meta, vocab_size: 84648}
    - {active: true, dtype: int, name: item_index, type: meta, vocab_size: 601}
    - {active: true, dtype: int, name: seq_len, type: meta}
    - {active: true, dtype: int, name: item_id, source: item, type: categorical, vocab_size: 601}
    item_info: ../../data/redkiwi256/maxlen128/item_info.parquet
    label_col: {dtype: float, name: label}
    rebuild_dataset: false
    test_data: ../../data/redkiwi256/maxlen128/test_longctr.parquet
    train_data: ../../data/redkiwi256/maxlen128/train_longctr.parquet
    user_info: ../../data/redkiwi256/maxlen128/user_info.parquet
    valid_data: ../../data/redkiwi256/maxlen128/valid_longctr.parquet
