# TimeMixer model hyperparameters

model_params:
  d_model:
    type: categorical
    choices: [64, 128, 256, 512]

  d_ff:
    type: categorical
    choices: [128, 256, 512, 1024, 2048]

  e_layers:
    type: categorical
    choices: [1, 2, 3]

  dropout:
    type: float
    min: 0.0
    max: 0.5

  down_sampling_layers:
    type: categorical
    choices: [0, 1, 2]

  down_sampling_window:
    type: categorical
    choices: [1, 2]

  channel_independence:
    type: categorical
    choices: [0, 1]
